"""
Convert Depth Anything V2 Small → TFLite menggunakan isolated environment.

Gunakan script ini dari fresh Python (bukan venv backend yang sudah banyak deps):

    python -m venv conv_venv
    conv_venv\\Scripts\\pip install torch torchvision transformers
    conv_venv\\Scripts\\pip install ai-edge-torch tensorflow
    conv_venv\\Scripts\\python convert_depth_to_tflite.py

Atau, jika ingin menggunakan ONNX Runtime di Flutter (lebih mudah):
    File ONNX sudah ada di: mobile/assets/models/depth_anything_v2_small.onnx
    Gunakan package: ort_flutter di pubspec.yaml
    
Script ini menggunakan PyTorch → ONNX Simplifier → TFLite via tf.lite.TFLiteConverter
"""
import sys
import os
import numpy as np
from pathlib import Path

ASSETS_DIR  = Path(__file__).parents[2] / "mobile" / "assets" / "models"
ONNX_PATH   = ASSETS_DIR / "depth_anything_v2_small.onnx"
TFLITE_PATH = ASSETS_DIR / "depth_anything_v2_small.tflite"
ASSETS_DIR.mkdir(parents=True, exist_ok=True)

print("=" * 60)
print("Depth Anything V2 Small  →  TFLite (via ONNX simplifier)")
print("=" * 60)

# ── 1. Simplify ONNX model ───────────────────────────────────
print("\n[1/3] Simplifying ONNX model...")
try:
    import onnx
    from onnxsim import simplify

    onnx_model = onnx.load(str(ONNX_PATH))
    simplified_model, check = simplify(onnx_model, input_shapes={"pixel_values": [1, 3, 518, 518]})
    if check:
        simplified_path = ONNX_PATH.with_stem(ONNX_PATH.stem + "_simplified")
        onnx.save(simplified_model, str(simplified_path))
        print(f"  ✓ Simplified ONNX: {simplified_path.name}")
        ONNX_PATH = simplified_path
    else:
        print("  ⚠ Simplification check failed, using original")
except ImportError:
    print("  onnxsim not installed, skipping simplification")
    print("  Install: pip install onnxsim")

# ── 2. Convert ONNX → TF SavedModel via onnx2tf properly ────
print(f"\n[2/3] ONNX → TFLite (direct via onnx2tf API)...")
try:
    import onnx2tf
    onnx2tf.convert(
        input_onnx_file_path=str(ONNX_PATH),
        output_folder_path=str(ASSETS_DIR / "depth_tf"),
        non_verbose=True,
        output_tfv1_pb=False,
    )
    # Find .tflite output
    tflite_files = list((ASSETS_DIR / "depth_tf").rglob("*.tflite"))
    if tflite_files:
        import shutil
        shutil.copy(tflite_files[0], TFLITE_PATH)
        print(f"  ✓ TFLite: {TFLITE_PATH.name} ({TFLITE_PATH.stat().st_size/1e6:.1f} MB)")
    else:
        raise FileNotFoundError("No .tflite generated by onnx2tf")
except Exception as e:
    print(f"  Failed: {e}")
    print("\nAlternative: Use ONNX Runtime for Flutter (ort_flutter package)")
    print("The ONNX model is already at:")
    print(f"  {ONNX_PATH}")
    print(f"  Size: {ONNX_PATH.stat().st_size/1e6:.1f} MB")
    print("\nUpdate pubspec.yaml:")
    print("  ort_flutter: ^1.0.0  # instead of tflite_flutter")
    sys.exit(0)  # Not an error - ONNX route is valid

# ── 3. Verify ────────────────────────────────────────────────
print(f"\n[3/3] Verifying...")
import tensorflow as tf
interp = tf.lite.Interpreter(model_path=str(TFLITE_PATH))
interp.allocate_tensors()
inp = interp.get_input_details()[0]
out = interp.get_output_details()[0]
print(f"  Input:  {inp['shape']}  {inp['dtype'].__name__}")
print(f"  Output: {out['shape']}  {out['dtype'].__name__}")
dummy = np.zeros(inp['shape'], dtype=np.float32)
interp.set_tensor(inp['index'], dummy)
interp.invoke()
res = interp.get_tensor(out['index'])
print(f"  OK: output shape {res.shape}")
print(f"\n  ✅ {TFLITE_PATH.name}  ({TFLITE_PATH.stat().st_size/1e6:.1f} MB)")
